# Generated by Django 4.2.20 on 2025-04-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_androidapp_status_alter_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapp',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/app_logo/'),
        ),
    ]
