# Generated by Django 4.2.20 on 2025-04-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_androidapp_app_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapp',
            name='app_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
